parameter_defaults: 
  OctaviaControlNetwork:
    description: The name for the neutron network used for the amphora control network
    type: string
    default: 'lb-mgmt-net'
  OctaviaControlSubnet:
    description: The name for the neutron subnet used for the amphora control network
    type: string
    default: 'lb-mgmt-subnet'
  OctaviaControlSecurityGroup:
    description: The name for the neutron security group used to control access on the amphora control network
    type: string
    default: 'lb-mgmt-sec-group'
  OctaviaControlSubnetCidr:
    description: Subnet for amphora control subnet in CIDR form     
    type: string
    default: '192.168.129.0/24'
  OctaviaControlSubnetGateway:
    description: IP address for control network gateway
    type: string
    default: '192.168.129.1'
  OctaviaControlSubnetPoolStart:
    description: First address in amphora control subnet address pool.
    type: string
    default: '192.168.129.2'
  OctaviaControlSubnetPoolEnd:
    description: First address in amphora control subnet address pool.
    type: string
    default: '192.168.129.250'
